api.urls:
  path: '/urls/{id}'
  defaults: {command: 'Duodraco\UrlShortener\Context\Command\Url'}
  requirements: { hash: '[[:alnum:]]+'}
  methods: [GET]

api.register:
  path: '/users/{userid}/urls'
  defaults: {command: 'Duodraco\UrlShortener\Context\Command\CreateUrl'}
  requirements: { hash: '[[:alnum:]]+'}
  methods: [POST]

api.stats:
  path: '/stats'
  methods: [GET]

api.user.stats:
  path: '/users/{userId}/stats'
  methods: [GET]

api.url.stats:
  path: '/stats/{id}'
  methods: [GET]

api.delete:
  path: '/urls/{id}'
  methods: [DELETE]

api.create.user:
  path: '/users'
  defaults: {command: 'Duodraco\UrlShortener\Context\Command\CreateUser'}
  methods: [POST]

api.delete.user:
  path: '/user/{userId}'
  methods: [DELETE]