services:
  file.locator:
    class: Symfony\Component\Config\FileLocator
    arguments: ['%app.path%/config/']
  pdo:
    class: PDO
    arguments:
      - "%pdo.dsn%"
      - "%pdo.user%"
      - "%pdo.pw%"
      - "%pdo.options%"
  pdoDriver:
    class: Drakojn\Io\Driver\Pdo
    arguments: ["@pdo"]
    public: false
    lazy: true
  application.web:
    class: Duodraco\UrlShortener\Services\Application
    arguments: ["@service_container"]
  logger.syslog.handler:
    class: Monolog\Handler\ErrorLogHandler
  app.logger:
    class: Monolog\Logger
    arguments: ['gaia']
    calls:
      - ['pushHandler', ["@logger.syslog.handler"]]
  hasher:
    class: Hashids\Hashids
    arguments: ["%default.salt%"]
  map.url:
    class: Drakojn\Io\Mapper\Map
    public: false
    arguments:
      localName: Duodraco\UrlShortener\Data\Url
      remoteName: url
      identifier: id
      properties:
        id: id
        hash: hash
        url: url
        userHash: user_hash
        hits: hits
  mapper.url:
    class: Duodraco\UrlShortener\Services\Persistence\Mapper
    arguments: ["@pdoDriver", "@map.url"]
  map.user:
    class: Drakojn\Io\Mapper\Map
    public: false
    arguments:
      localName: Duodraco\UrlShortener\Data\User
      remoteName: user
      identifier: id
      properties:
        id: id
        hash: hash
        alias: alias
  mapper.user:
    class: Duodraco\UrlShortener\Services\Persistence\Mapper
    arguments: ["@pdoDriver", "@map.user"]